### ISSUE TITLE
route.js第130行的空格有问题，console报错

### ISSUE THREAD

**Issue by huangzhike** [kliuj/spa-routers#1]
130行的callback && callback(transition)

**Comment by huangzhike** [comment]
应该是test.html没加`<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />`的缘故

**Comment by kliuj** [comment]
@huangzhike   感谢提醒，已经改了，我没想到空格也会出现编码问题

**Comment by kliuj** [comment]
@huangzhike  你好，我这里找到实际原因，是因为我那个空格使用的是全角空格，全角空格在浏览器会被解析成中文汉子，所以非uft-8的情况下就报错了
